<%@page pageEncoding="UTF-8" %>
<!DOCTYPE html>
<html><head>
<meta http-equiv="content-type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="viewport" content="width=device-width initial-scale=1">
<link rel="stylesheet" href="${pageContext.request.contextPath}/resources/mcgza//stylesheet.css">
<title>MyLife</title>
</head>

<body class="termspage">
	<div id="mainbox">
		<div class="content">
         <h2>Terms and Conditions</h2>
         	<p><b>MyLife</b> is a subscription service which contains 
Various Lifestyle &amp; Fitness Content - Workouts, Martial Arts, 
Healthy Eating &amp; More…</p>
           <ul>
                	<li>1. Charges will be made on your mobile bill or deducted from your prepaid balance. Network charges may apply.</li><br>
                    <li>2. <b>For Customer Support: </b> <br>Email Us: care@collectcent.com.  <br>Call Us@: 27 (0)800981275</li><br>
                    <li>3. By clicking "Subscribe Now", you agree to be subscribed for R7 per Day</li><br>
                    <li>4.By giving your mobile number to us through the
 internet, via our online adverts or any other promotions, you will gain
 access to content of MyLife . You confirm that you are over the age of 
16 and have the permission of the bill payer</li><br>
                     <li>5. Parents Guidance Necessary for children below 16 </li><br>
                    <li>6. Should a mobile network operator encounter 
failed delivery attempts of a premium message prior to a user sending in
 the STOP command / Unsubscribe Instructions, the network may still 
attempt to re-deliver the failed message even after the STOP command / 
Unsubscribe method has been sent to the promoter. Users understand and 
accept that the promoter has no control in this matter. However the 
promoter will ensure that no new premium messages are generated by the 
promoter after receipt of a valid stop command. All STOP commands / 
Unsubscribe method are answered by a free text confirming the STOP 
command / Unsubscribe method and the cancellation of the subscription as
 explained in the Unsubscribe section of this page.</li><br>
                   
                    <li>7. To Unsubscribe from this service, send <b>STOP</b> to <b>XXXX</b> </li><br>
                    <li>8. Any Smartphone with video Player is compatible for our service</li><br>
                    <li>9. Service provided by: Collectcent Digital Media Pvt. Ltd.</li><br>
                    <li>10. <b>Collectcent Digital Media Pvt Ltd</b> is a
 member of WASPA and is bound by the WASPA Code of Conduct.
Customers have the right to approach WASPA to lodge a complaint in 
accordance with the WASPA complaints procedure. Collectcent Digital 
Media Pvt Ltd may be required to share information relating to a service
 or a customer with WASPA for the purpose of resolving a complaint. <b>WASPA website: www.waspa.org.za</b></li>
                 </ul>
         
  </div>
	</div>


</body></html>